runtime: java17
instance_class: F1

env_variables:
  SPRING_PROFILES_ACTIVE: "prod"
  SPRING_CLOUD_GCP_SQL_DATABASE_NAME: "dbastroglow"
  SPRING_CLOUD_GCP_SQL_INSTANCE_CONNECTION_NAME: "astroglowfirebase-d2411:asia-southeast1:dbastroglow"

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10

handlers:
  - url: /.*
    script: auto
    secure: always

inbound_services:
  - warmup

# Cloud SQL configuration
beta_settings:
  cloud_sql_instances: astroglowfirebase-d2411:asia-southeast1:dbastroglow

# Java specific configuration
env: standard
entrypoint: java -jar target/AstroGlow-0.0.1-SNAPSHOT.jar

# Memory settings
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10 